import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { generateProject } from '@forgestack/generator';
import { loadRegistry, createTemplateSource } from '../src/index.js';

/**
 * Dev helper: generate the sample Fastify + TS + MongoDB project to a directory
 * so we can `pnpm install && pnpm typecheck` the *output* and prove it compiles.
 *
 * Usage: tsx scripts/generate-sample.ts [outDir] [modules,csv]
 */
const outDir = process.argv[2] ?? '/tmp/forgestack-sample';
const modules = (process.argv[3] ?? 'mongodb').split(',');

const result = generateProject(
  { projectName: 'sample-api', description: 'Generated by ForgeStack', modules, packageManager: 'pnpm' },
  { registry: loadRegistry(), templates: createTemplateSource() },
);

rmSync(outDir, { recursive: true, force: true });
for (const file of result.files) {
  const full = join(outDir, file.path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, file.content, { mode: file.executable ? 0o755 : 0o644 });
}

console.log(`✓ Generated ${result.files.length} files → ${outDir}`);
console.log(`  modules: ${result.resolvedModules.join(' → ')}`);
if (result.warnings.length) {
  console.log('  warnings:');
  for (const w of result.warnings) console.log(`   - ${w}`);
}
console.log('\nFiles:');
for (const f of result.files) console.log(`   ${f.path}`);
